CFLAGS=-Wall -g

all:
	cc ${CFLAGS} ex6.c -o ex6
	cc ${CFLAGS} ex7.c -o ex7
	cc ${CFLAGS} ex8.c -o ex8
#	cc ${CFLAGS} ex9.c -o ex9
	cc ${CFLAGS} ex10.c -o ex10
	cc ${CFLAGS} ex11.c -o ex11
	cc ${CFLAGS} ex12.c -o ex12
	cc ${CFLAGS} ex13.c -o ex13
	cc ${CFLAGS} ex14.c -o ex14
	cc ${CFLAGS} ex15.c -o ex15

clean:
	rm -f ex{6,7,8,9,10,11,12,13,14,15}
